<?php

/**
 * JobeetAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class JobeetAffiliate extends BaseJobeetAffiliate
{
    public function __toString() {
        return $this->getUrl();
    }
}
