<?php

/**
 * JobeetCategoryAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class JobeetCategoryAffiliate extends BaseJobeetCategoryAffiliate
{
}
